[package]
edition = "2024"

name = "kutil"
description = "Kutil Utilities Collection"
version = "0.0.1"
rust-version = "1.90"

license = "MIT OR Apache-2.0"
repository = "https://github.com/tliron/kutil"
documentation = "https://docs.rs/kutil"
authors = ["Tal Liron"]

readme = "../README.md"

categories = []                                                 # https://crates.io/category_slugs
keywords = ["kutil", "cli", "http", "io", "transcoding"]

[dependencies]
# cli
anstream = { optional = true, version = "0.6.21" }
anstyle = { optional = true, version = "1.0.13" }
build-info = { optional = true, version = "0.0.42" }
clap = { optional = true, version = "4.5.49", features = ["derive"] }
clap_complete_command = { optional = true, version = "0.6.1" }
clap_mangen = { optional = true, version = "0.2.30" }
kutil-cli-macros = { optional = true, version = "=0.0.6" }
owo-colors = { optional = true, version = "4.2.3" }
time = { optional = true, version = "0.3.44", features = ["macros"] }
tracing-journald = { optional = true, version = "0.3.1" }
tracing-subscriber = { optional = true, version = "0.3.20", features = [
    "env-filter",
    "local-time",
] }

# http
axum = { optional = true, version = "0.8.6" }
axum-extra = { optional = true, version = "0.10.3" }
axum-server = { optional = true, version = "0.7.2" }
base64-simd = { optional = true, version = "0.8.0" }
duration-str = { optional = true, version = "0.17.0" }
http = { optional = true, version = "1.3.1" }
http-body = { optional = true, version = "1.0.1" }
httpdate = { optional = true, version = "1.0.3" }
moka = { optional = true, version = "0.12.11", features = ["future"] }
rustls = { optional = true, version = "0.23.32" }
rustls-acme = { optional = true, version = "0.14.1", features = ["axum"] }
rustls-pemfile = { optional = true, version = "2.2.0" }
rustls-pki-types = { optional = true, version = "1.12.0" }
thiserror = { optional = true, version = "2.0.17" }
tokio-util = { optional = true, version = "0.7.16", features = ["io-util"] }
tower = { optional = true, version = "0.5.2" }
tower-http = { optional = true, version = "0.6.6", features = ["fs"] }
url = { optional = true, version = "2.5.7" }
urlencoding = { optional = true, version = "2.1.3" }

# io
futures = { optional = true, version = "0.3.31" }
netdev = { optional = true, version = "0.38.2" }
utf8-chars = { optional = true, version = "3.0.5" }

# std
bimap = { optional = true, version = "0.6.3" }
bytes = { optional = true, version = "1.10.1" }
bytestring = { optional = true, version = "1.5.0" }
kutil-std-macros = { optional = true, version = "=0.0.2" }
num-traits = { optional = true, version = "0.2.19" }
papaya = { optional = true, version = "0.2.3" }
rapidhash = { optional = true, version = "4.1.0", features = ["unsafe"] }

# cli, http, transcoding
tracing = { optional = true, version = "0.1.41" }

# http, transcoding
async-compression = { optional = true, version = "0.4.32" }
pin-project = { optional = true, version = "1.1.10" }

# http, io, transcoding
tokio = { optional = true, version = "1.48.0" }

[build-dependencies]
# cli
build-info-build = { optional = true, version = "0.0.42" }

[dev-dependencies]
# For examples/tower_caching.*
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.6", features = ["trace"] }
tracing-subscriber = { version = "0.3.20", features = [
    "env-filter",
    "local-time",
] }

[features]
## CLI utilities.
cli = [
    "dep:anstream",
    "dep:owo-colors",
    "dep:time",
    "dep:tracing",
    "dep:tracing-journald",
    "dep:tracing-subscriber",
]
## Clap utilities.
clap = [
    "dep:clap",
    "dep:clap_complete_command",
    "dep:clap_mangen",
    "dep:anstyle",
    "dep:build-info",
    "dep:build-info-build",
]

## HTTP utilities.
http = [
    "dep:async-compression",
    "dep:base64-simd",
    "dep:duration-str",
    "dep:http",
    "dep:http-body",
    "dep:httpdate",
    "dep:moka",
    "dep:pin-project",
    "dep:thiserror",
    "dep:tracing",
    "dep:tokio",
    "dep:tokio-util",
    "dep:url",
    "dep:urlencoding",
    "io",
    "std",
    "async",
    "transcoding",
    "derive",
    "fast_collections",
    "immutable",
]
## ACME support for TLS.
acme = ["dep:rustls-acme"]
## Axum utilities.
axum = [
    "dep:axum",
    "dep:axum-extra",
    "dep:axum-server",
    "tokio/signal",
    "tower/util",
]
## File utilities for Tower.
file = ["tower", "dep:tower-http"]
## Moka implementation for cache.
moka = ["dep:moka"]
## TLS utilities for axum.
tls = [
    "dep:rustls",
    "dep:rustls-pemfile",
    "dep:rustls-pki-types",
    "axum-server/tls-rustls",
]
## Tower utilities.
tower = ["dep:tower"]

## I/O utilities.
io = [
    "dep:futures",
    "dep:netdev",
    "dep:tokio",
    "dep:utf8-chars",
    "tokio/rt",
    "tokio/io-util",
]

## Enable blocking implementations.
blocking = []
## Enable async implementations.
async = []

## Standard library utilities.
std = ["dep:num-traits"]
## Enable bimap
bimap = ["dep:bimap"]
## Enable fast collections.
fast_collections = ["dep:bimap", "dep:papaya", "dep:rapidhash"]
## Enable serde support.
serde = ["bytes?/serde", "bytestring?/serde"]
## Enable immutable implementations, e.g. `Bytes` and `ByteString`.
immutable = ["dep:bytes", "dep:bytestring"]

## Transcoding utilities.
transcoding = [
    "dep:async-compression",
    "dep:pin-project",
    "dep:tracing",
    "dep:tokio",
    "async-compression/tokio",
    "async-compression/brotli",
    "async-compression/deflate",
    "async-compression/gzip",
    "async-compression/zstd",
    "tokio/io-util",
    "std",
    "derive",
    "immutable",
]

## Include procedural macros for `derive`.
derive = ["dep:kutil-cli-macros", "dep:kutil-std-macros"]

[[example]]
name = "depict"
required-features = ["cli", "std"]

[[example]]
name = "depict_markup"
required-features = ["cli"]

[[example]]
name = "depict_derive"
required-features = ["cli", "derive"]

[[example]]
name = "join_conjunction"
required-features = ["std"]

[[example]]
name = "tower_caching_basic"
required-features = ["http", "tower", "axum", "moka"]

[[example]]
name = "tower_caching_advanced"
required-features = ["http", "tower", "axum", "moka"]

# https://stackoverflow.com/a/61417700
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
