#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

for E in $(cargo run --example --package kutil 2>&1 | grep --extended-regexp '^    ' | sort); do
    if [[ "$E" != tower_* ]]; then
        m "\nexample: $E\n" "$RED"
    	cargo +nightly run --quiet --example "$E" --package kutil --features=cli,std,derive
    fi
done
