[package]
edition = "2021"

name = "kutil-io"
description = "I/O utilities from Kutil"
version = "0.0.1"
rust-version = "1.84"

license = "MIT OR Apache-2.0"
repository = "https://github.com/tliron/rust-kutil"
documentation = "https://docs.rs/kutil-io"
authors = ["Tal Liron"]

readme = "../../README.md"

categories = [] # https://crates.io/category_slugs
keywords = ["kutil", "io"]

[dependencies]
bytes = "1.9.0"
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["rt"] }

[features]
default = [
  "blocking",
  "async",
]
blocking = []
async = []
