[package]
edition = "2024"

name = "kutil-io"
description = "I/O utilities from Kutil"
version = "0.0.1"
rust-version = "1.85"

license = "MIT OR Apache-2.0"
repository = "https://github.com/tliron/rust-kutil"
documentation = "https://docs.rs/kutil-io"
authors = ["Tal Liron"]

readme = "../../README.md"

categories = []            # https://crates.io/category_slugs
keywords = ["kutil", "io"]

[dependencies]
bytes = "1.10.1"
futures = "0.3.31"
netdev = "0.34.0"
network-interface = "2.0.1"
tokio = { version = "1.44.2", features = ["rt"] }

[features]
default = ["blocking", "async"]
blocking = []
async = []
